#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Gal Diskin
# SPDX-License-Identifier: MIT
# Regenerate the Python gRPC stubs in ss_driver/_proto from the vendored OpenShell
# protocol files in proto/. Run after updating proto/; commit the result.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
out="$here/ss_driver/_proto"
rm -rf "$out"
mkdir -p "$out"
uv run --project "$here" --group dev python -m grpc_tools.protoc \
  -I "$here/proto" \
  --python_out="$out" \
  --grpc_python_out="$out" \
  "$here/proto/credential_driver.proto" \
  "$here/proto/datamodel.proto" \
  "$here/proto/extension.proto" \
  "$here/proto/options.proto"
# protoc emits top-level imports (import datamodel_pb2 ...); make them package-relative.
perl -pi -e 's/^import (\w+_pb2) as /from . import $1 as /' "$out"/*.py
cat > "$out/__init__.py" <<'PY'
"""Generated gRPC stubs for the OpenShell credential-driver protocol.

Generated by gen_protos.sh from the vendored files in proto/ (Apache-2.0, NVIDIA).
Do not edit by hand; regenerate instead.
"""
PY
echo "generated stubs in ss_driver/_proto"
